INFO     test_present_activate:conftest.py:49 ===> Test test_present_activate started
INFO     WDM:logger.py:11 ====== WebDriver manager ======
INFO     WDM:logger.py:11 Get LATEST chromedriver version for google-chrome 104.0.5112
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): chromedriver.storage.googleapis.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://chromedriver.storage.googleapis.com:443 "GET /LATEST_RELEASE_104.0.5112 HTTP/1.1" 200 13
INFO     WDM:logger.py:11 Driver [/home/GoorooG/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:54869/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": []}}}, "desiredCapabilities": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": []}}}
DEBUG    urllib3.connectionpool:connectionpool.py:228 Starting new HTTP connection (1): localhost:54869
DEBUG    urllib3.connectionpool:connectionpool.py:456 http://localhost:54869 "POST /session HTTP/1.1" 200 753
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
INFO     test_present_activate:conftest.py:94 start with browser<<chrome>>
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:54869/session/5449d4f2721ddda77cc863e6961ab655/window/maximize {}
DEBUG    urllib3.connectionpool:connectionpool.py:456 http://localhost:54869 "POST /session/5449d4f2721ddda77cc863e6961ab655/window/maximize HTTP/1.1" 200 54
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:54869/session/5449d4f2721ddda77cc863e6961ab655/url {"url": "http://192.168.31.204:8081/desktops/ipod-classic"}
DEBUG    urllib3.connectionpool:connectionpool.py:456 http://localhost:54869 "POST /session/5449d4f2721ddda77cc863e6961ab655/url HTTP/1.1" 200 14
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:347 POST http://localhost:54869/session/5449d4f2721ddda77cc863e6961ab655/element {"using": "css selector", "value": "li.active a"}
DEBUG    urllib3.connectionpool:connectionpool.py:456 http://localhost:54869 "POST /session/5449d4f2721ddda77cc863e6961ab655/element HTTP/1.1" 404 774
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
ERROR    test_present_activate:conftest.py:103 Oooops i got: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=104.0.5112.79)
Stacktrace:
#0 0x555a43035403 <unknown>
#1 0x555a42e3b778 <unknown>
#2 0x555a42e1c7f8 <unknown>
#3 0x555a42e93f6b <unknown>
#4 0x555a42ea32a5 <unknown>
#5 0x555a42e908f3 <unknown>
#6 0x555a42e660d8 <unknown>
#7 0x555a42e67205 <unknown>
#8 0x555a4307ce3d <unknown>
#9 0x555a4307fdb6 <unknown>
#10 0x555a4306613e <unknown>
#11 0x555a430809b5 <unknown>
#12 0x555a4305a970 <unknown>
#13 0x555a4309d228 <unknown>
#14 0x555a4309d3bf <unknown>
#15 0x555a430b7abe <unknown>
#16 0x7f87e56dee2d <unknown>

DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:347 GET http://localhost:54869/session/5449d4f2721ddda77cc863e6961ab655/screenshot {}
DEBUG    urllib3.connectionpool:connectionpool.py:456 http://localhost:54869 "GET /session/5449d4f2721ddda77cc863e6961ab655/screenshot HTTP/1.1" 404 774
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:347 DELETE http://localhost:54869/session/5449d4f2721ddda77cc863e6961ab655 {}
DEBUG    urllib3.connectionpool:connectionpool.py:456 http://localhost:54869 "DELETE /session/5449d4f2721ddda77cc863e6961ab655 HTTP/1.1" 200 14
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:398 Finished Request
INFO     test_present_activate:conftest.py:111 <=== Test test_present_activate finished